<div class="table-responsive">
    <table class="table table-striped
    table-hover	
    table-bordered
    align-middle">
        <thead class="table-light">
            <tr>
                <th>Category Name</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            <?php foreach ($categories as $category) : ?>
                <tr class="<?= $category->id ?>">
                    <td scope="row">
                        <?php if ($wantEdit === $category->id) : ?>
                            <form action="updateCategory/<?= $category->id ?>" method="post">
                                <input type="text" name="categoryName" class="form-control mb-1" value="<?= $category->name ?>">
                                <button type="submit" class="btn btn-success">Edit</button>
                            </form>
                        <?php
                        else :
                        ?>
                            <?= $category->name ?>
                        <?php endif ?>
                    </td>
                    <td>
                        <?php if ($wantEdit === $category->id) : ?>
                            <a class="btn btn-warning" href="adminCategories">Cancel</a>
                        <?php
                        else :
                        ?>
                            <a class="btn btn-primary" href="editCategory/<?= $category->id ?>">Edit</a>
                        <?php endif ?>
                        <a class="btn btn-danger" href="deleteCategory/<?= $category->id ?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php
require './Templates/registerCategory.phtml';
?>