<div class="container d-flex justify-content-center h-100 w-100">
    <form method="POST" action="updateShop/<?= $shop->id ?>" class="d-flex flex-column h-100 w-50 align-items-center">
        <div class="mb-3 w-100">
            <label for="productName" class="form-label">Shop name</label>
            <input type="text" name="shopName" class="form-control" id="ProductName" value="<?= $shop->name ?>">
        </div>
        <div class="mb-3 w-100">
            <label for="productDescription" class="form-label">Shop address</label>
            <input type="text" name="shopAddress" class="form-control" id="productDescription" value="<?= $shop->address ?>">
        </div>
        <div class="mb-3 w-100">
            <label for="imageURL" class="form-label">URL logo Shop</label>
            <input type="text" name="shopImage" class="form-control" id="imageURL" value="<?= $shop->shop_image ?>">
        </div>
        <button type="submit" class="btn btn-primary">Edit Shop</button>
    </form>
</div>