<!DOCTYPE html>
<html lang="en">

<!-- head -->

<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="./CSS/style.css">
    <title><?= $title ?></title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <!-- Elementos a la izquierda -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Shops</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Products</a>
                    </li>
                </ul>

                <!-- Logo o nombre del sitio centrado -->
                <a class="navbar-brand" href="home"><img id="logo" src="./images/logo-tpe.png" alt="Logo"></a>

                <!-- Elementos a la derecha -->
                <ul class="navbar-nav ml-auto">
                    <?php if (!isset($_SESSION['logueado'])) : ?><!-- aca hay que comprobar si el usuario no está logueado -->
                        <li class="nav-item">
                            <a class="nav-link" href="signup">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="signin">Sign In</a>
                        </li>
                    <?php
                    else :
                    ?>
                        <li class="nav-item">
                            <a class="nav-link" href="signout">Sign Out</a>
                        </li>
                    <?php endif ?>
                </ul>
            </div>
        </nav>
    </header>