<!-- start carousel -->
<div class="container-carousel">
    <div id="carouselExampleRide" class="carousel slide m-4" data-bs-ride="true">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="./images/hamburguesas.png" class="d-block w-100 carousel-img" alt="hamburguesas">
            </div>
            <div class="carousel-item">
                <img src="./images/hot-dogs.jpg" class="d-block w-100 carousel-img" alt="hot dogs">
            </div>
            <div class="carousel-item">
                <img src="./images/empanadas.jpg" class="d-block w-100 carousel-img" alt="empanadas">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
<!-- end carousel -->