<div class="container text-center">
    <h1>Welcome to HereFood!</h1>
    <h2>HereFood: Connecting Gastronomic Passion with the World.</h2>
</div>

<div class="container text-center">
    <p class="h3">In the competitive world of gastronomy, standing out from the crowd is essential. That's why at HereFood, we have created a platform specifically designed to help businesses in the gastronomic industry effectively showcase their products, regardless of their size or location.</p>
</div>
<!-- start carousel -->
<div class="container-carousel">
    <div id="carouselExampleRide" class="carousel slide m-4" data-bs-ride="true">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="./images/hamburguesas.png" class="d-block w-100 carousel-img" alt="hamburguesas">
            </div>
            <div class="carousel-item">
                <img src="./images/hot-dogs.jpg" class="d-block w-100 carousel-img" alt="hot dogs">
            </div>
            <div class="carousel-item">
                <img src="./images/empanadas.jpg" class="d-block w-100 carousel-img" alt="empanadas">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
<!-- end carousel -->

<div class="accordion" id="accordionExample">
    <h3>What We Offer?</h3>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Global Exposure:
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <p> HereFood connects you with food enthusiasts worldwide, 
giving you the opportunity to reach new customers and international markets.</p>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Customized Profile:
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <p>Create a unique profile for your business
with high-quality photos, detailed descriptions, and the ability to showcase your menu online.</p>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Effective Marketing:
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <p>Our team of gastronomic marketing experts will provide
you with tips and strategies to boost your online presence and attract more customers.</p>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
      Reviews and Ratings:
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <p>Customers can leave reviews and ratings, helping you build a 
solid and trustworthy reputation.</p>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
      Gastronomic Community:
      </button>
    </h2>
    <div id="collapseFive" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <p>Join a passionate community of chefs, restaurants, 
food trucks, and food lovers who share your enthusiasm for gastronomy.</p>
      </div>
    </div>
  </div>
</div>