<div class="container vh-100 w-100">
   
    <div class="container w-100 row row-cols-3" data-bs-spy="scroll">
        <?php
        foreach($products[0] as $product) : ?> 
        <div class="card col">
            <img src="<?= $product->product_image ?>" class="card-img-top" alt="<?= $product->product_description ?>">
            <div class="card-body">
                <h5 class="card-title"><?= $product->name ?></h5>
                <p class="card-text"><?= $product->product_description ?></p>
                <p><?= $product->stock ?></p>
                <p><?= $product->price ?></p>
            </div>
        </div>
        <?php endforeach;
        
        ?>
    </div>


</div>