<div class="container w-100 row row-cols-3">
    <?php
    foreach ($products as $product) : ?>
        <div class="card col g-4">
            <img src="<?= $product->product_image ?>" class="card-img-top" alt="<?= $product->product_description ?>">
            <div class="card-body">
                <h5 class="card-title"><?= $product->productName ?></h5>
                <p class="card-text"><?= $product->product_description ?></p>
                <?php if ($product->stock > 0) : ?>
                    <p>Stock: <?= $product->stock ?></p>
                <?php
                else :
                ?>
                    <p class="text-muted">No hay stock</p>
                <?php
                endif;
                ?>
                <p>$ <?= $product->price ?></p>
                <span class="badge text-bg-secondary"><?= $product->categoryName ?></span>
                <a href="showShop/<?= $product->shopId ?>">
                    <span class="badge text-bg-primary">
                        <?= $product->shopName ?>
                    </span>
                </a>
                <?php
                if ($showOption) { ?>
                    <a class="btn btn-danger" href="deleteProduct/<?= $product->idProduct ?>">Delete</a>
                <?php
                }
                ?>
            </div>
        </div>
    <?php endforeach ?>
</div>