<div class="container d-flex justify-content-center h-100 w-100">
    <form method="POST" action="addShop" class="d-flex flex-column h-100 w-50 align-items-center">
        <div class="mb-3 w-100">
            <label for="productName" class="form-label">Shop name</label>
            <input type="text" name="shopName" class="form-control" id="ProductName">
        </div>
        <div class="mb-3 w-100">
            <label for="productDescription" class="form-label">Shop address</label>
            <input type="text" name="shopAddress" class="form-control" id="productDescription">
        </div>
        <div class="mb-3 w-100">
            <label for="imageURL" class="form-label">URL logo Shop</label>
            <input type="text" name="shopImage" class="form-control" id="imageURL">
        </div>
        <button type="submit" class="btn btn-primary">Add Shop</button>
    </form>
</div>
<p class="text-muted text-center my-5">Before creation you must coordinate with the site administrators for payment.</p>