<div class="container d-flex justify-content-center h-100 w-100 g-2">

    <div class="row">
        <?php
        foreach ($shops as $shop) : ?>
            <div class="col-md-4 mb-4">
                <a class="card nav-link" href="showProducts/<?= $shop->id ?>">
                    <img src="<?= $shop->shop_image ?>" class="card-img-top h-25" alt="<?= $shop->name ?>" title="<?= $shop->name ?>">
                    <div class="card-body">
                        <h5 class="card-title"><?= $shop->name ?></h5>
                        <span class="badge text-bg-secondary"><?= $shop->address ?></span>
                    </div>
                </a>
            </div>
        <?php endforeach ?>
    </div>
</div>