<div class="container vh-100 d-flex justify-content-center align-items-center">
  <div class="container h-100 d-flex flex-column justify-content-evenly align-items-center">
  <h1>Sign Up</h1>
    <form class="h-50 w-50">
      <div class="mb-3 w-100">
        <label for="exampleInputUsername" class="form-label">Username</label>
        <input type="text" class="form-control" id="exampleInputUsername">
      </div>
      <div class="mb-3 w-100">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1">
      </div>
      <div class="mb-3 w-100">
        <label for="exampleInputPassword2" class="form-label">Confirm Password</label>
        <input type="password" class="form-control" id="exampleInputPassword2">
      </div>
      <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
  </div>
</div>