<div class="container vh-100 d-flex flex-column justify-content-center align-items-center text-center">
  <div class="container h-100 d-flex flex-column justify-content-evenly align-items-center">
  <h1>Sign Up</h1>
    <form method="POST" action="createUser" class="h-50 w-50">
      <div class="mb-3 w-100">
        <label for="exampleInputUsername" class="form-label">Username</label>
        <input type="text" name="username" class="form-control" id="exampleInputUsername">
      </div>
      <div class="mb-3 w-100">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
      </div>
      <div class="mb-3 w-100">
        <label for="exampleInputPassword2" class="form-label">Confirm Password</label>
        <input type="password" name="passwordConfirm" class="form-control" id="exampleInputPassword2">
      </div>
      <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
  </div>
  <p>In HereFood, we understand that the passion for food transcends 
borders and languages.
Whether you speak Spanish, English, or any other language,
 we are here to help you showcase your products to the world. Join us today and let us be your partner on the path to gastronomic success. Together, we will take your business to the next level!</p>
 <p>HereFood: Where Gastronomic Passion Meets the World</p>
</div>

