<div class="container vh-100 d-flex justify-content-center align-items-center">
  <div class="container h-100 d-flex flex-column justify-content-evenly align-items-center">
  <h1>Sign In</h1>
    <form action="user" method="POST" class="h-50 w-50">
      <div class="mb-3">
        <label for="exampleInputUsername" class="form-label">Username</label>
        <input type="text" name="userName" class="form-control" id="exampleInputUsername">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" name="userPassword" class="form-control" id="exampleInputPassword1">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>